# Generated by Django 2.1.7 on 2020-04-01 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vvp', '0002_auto_20200401_1000'),
        ('vvp', '0002_auto_20200331_1813'),
    ]

    operations = [
    ]
