# Generated by Django 2.1.7 on 2020-04-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvp', '0002_auto_20200401_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='current_employment_status',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
